angular.module('HistoryDetailCtrl', [])

// For the View which is Displaying a History Event or creating a New History Event
.controller('HistoryDetailCtrl', ['$rootScope', '$scope', '$state', 'History', 'Job', 'util',
	function($rootScope, $scope, $state, History, Job, util) {

	  $scope.bNewItem = false;		// Just looking at an existing Event by default
	  var jobId = '';							// Every History Event is associated with a Job

	  function getHistory() {
	  	var historyId = $state.params.eventId;  // A single Event to Display
	  	jobId = $state.params.jobId;						// Or maybe all Events for a Job

	  	if (jobId.indexOf('-New') > 0) {				// Creating a new Event for a Job
	  		$scope.bNewItem = true;								// Toggle the View to Edit Mode
	  		jobId = jobId.replace('-New', '');		// Isolate the jobId
	  		return newHistory();									// Return a default Event Item
	  	}

	  	var filter = {"filter":
		                  {
		                    "where": {"mobhistSeq": historyId},
		                    "include": "jobs"
		                  }
	                	}; 
	        // By default, find a singleEvent

	    if (jobId >= 0) {
	    	filter.filter.where = {"jobId": jobId};
	    }		// Or, alternatively, all Events for a Job...

      History.find(filter)	// Method generated by the LoopBack Angular SDK
        .$promise
        .then(function(results) {
        	if (results.length === 0) {
        		window.location.href = "#/tab/history";
        			// If no Events found, show them all...
        		return;
        	}

					$scope.history = results;
						// an Array of one or more Events

		      $scope.history.sort(sortByEventTime).reverse();
			    function sortByEventTime(a,b) {
			    	return a.mobhistStamp - b.mobhistStamp;
			    }
			    	// sort them from Most Recent Event on down

					$scope.historyData = new Array($scope.history.length);
						// Each Event will have to have Metadata to control its Display...

					for (var i = 0; i < $scope.history.length; i++) {
						$scope.historyData[i] = $scope.combineValuesAndLabels($scope.history[i], $rootScope.historyMetadata);
							// Set up the Metadata to control the Display of each Event...

						$scope.base.bDataChanged = false;
							// Just viewing them, so we shouldn't display a Save Button

						if (jobId >= 0) {
							$rootScope.tabHeader = "History Events for Job: " + jobId;
						}
						else {
							$rootScope.tabHeader = "Job History Event";
						}
							// Set up an appropriate View Header Title...

						var jobProperty = util.findArrayItemByKey($scope.historyData[i], "property", "jobId");
						if (jobProperty) {
							jobId = jobProperty.value;
	          	jobProperty.generatedValue = $scope.generateHeaderForModelInstance($scope.history[i].jobs, $rootScope.jobMetadata);
	          }
	          	// Set up a Friendlier Title for the Associated Job...
					}
        });
	  }

	  function newHistory() {
  		$scope.bNewItem = true;	// Display the Save Button...

			$scope.history = [{}];
			$scope.historyData = [];	// Set up the Containers to hold the Item and Metadata

			var idProperty = util.findArrayItemByKey($rootScope.historyMetadata.properties, "name", 'jobId');
			if (idProperty) {
				$scope.history[0][idProperty.name] = jobId;
			}	// ALWAYS associated with a specific JOB...

			$scope.historyData[0] = $scope.createNewItem($scope.history[0], $rootScope.historyMetadata);
				// Create the Default Item and its Metadata...

			$rootScope.tabHeader = 'New History Event';
	  }

	  var defaultActionButtons = [];

	  var defaultActionButtons = [
	  ];  // No Default Actions because Events are immutable...

		$scope.showActionSheet = function() {
			if (jobId !== '') {
				var buttons = util.copyObject(defaultActionButtons);
			  buttons.push({ text: 'Add a History Event', command: 'addEvent'});
			  	// You can add another History Event from within the Context
			  	// of another Event because there is ALWAYS a jobId available...

				$scope.showActionSheetBase("Actions from this Event History", buttons, function(command) {
					 	switch (command) {
					 		case 'addEvent':
				 				window.location.href = '#/tab/history/-1/' + jobId + '-New';
				 					// This is the Route to create a new History Event for a Job
						 		break;
					 	}
				}, false);
			}
		}

		$scope.saveEvent = function() {
 			$scope.updateItem($scope.history[0], $scope.historyData[0], History, function(results) {
 				window.location.href = '#/tab/history/-1/' + jobId;
 					// Re-Display the Events for this Job.  The new one will be at the top...
 			}, $scope.bNewItem)
		}

	  $scope.generateHistoryHeader = function(item) {
	  	return $scope.generateHeaderForModelInstance(item, $rootScope.historyMetadata);
	  		// The Base Class generates meaningful Titles for any Entity...
	  }	

	  $scope.getModelMetadata(History, "historyMetadata", function(metadata) {
	  	$scope.getModelMetadata(Job, "jobMetadata", function(metadata) {
	  		// Once we are ensured to have all the Metadata we need
	  		getHistory();
	  			// Get the History Record(s)
	  	});
	  });


	}
])
